version: '3.8'

services:
  # MySQL Database Service
  mysql_db:
    image: mysql:8.0
    container_name: todo_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: todotasks
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./todotasks.sql:/docker-entrypoint-initdb.d/todotasks.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Backend Service
  backend:
    image: vimukthiserasinghe/todo-backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: todo_backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      mysql_db:
        condition: service_healthy

  # React Frontend Service
  frontend:
    image: vimukthiserasinghe/todo-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: todo_frontend
    restart: always
    ports:
      - "3000:80"

volumes:
  db_data:
